spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: Lbq123456
    url: jdbc:mysql://localhost:3306/news?useSSL=false&useUnicode=true&characterEncoding=utf8
    
logging:
  level:
    com.aowin.dao.*: debug